"""0002: real DDL for the balance_ledger addition + indexes on hot paths.

Revision ID: 0002_ledger_indexes
Revises: 0001_initial
Create Date: 2026-08-25

The baseline 0001 stamps the metadata-created schema. This revision captures
the post-baseline additions as explicit op.* DDL so future autogenerated
migrations diff against a real declared state:
  - idx_invoice_user_status   (my-services lookups, expiry sweeps)
  - idx_payment_order         (webhook claim_paid lookups)
  - idx_ledger_user           (wallet history)
"""
from __future__ import annotations

from alembic import op

revision = "0002_ledger_indexes"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_index("idx_invoice_user_status", "invoice",
                    ["user_id", "status"], unique=False)
    op.create_index("idx_payment_order", "Payment_report",
                    ["order_id"], unique=True)
    op.create_index("idx_ledger_user", "balance_ledger",
                    ["user_id", "id"], unique=False)


def downgrade() -> None:
    op.drop_index("idx_ledger_user", table_name="balance_ledger")
    op.drop_index("idx_payment_order", table_name="Payment_report")
    op.drop_index("idx_invoice_user_status", table_name="invoice")
